-- 1
SELECT nombre 
FROM peliculas;

-- 2
SELECT DISTINCT calificacion_edad 
FROM peliculas;

-- 3
SELECT nombre 
FROM peliculas 
WHERE calificacion_edad IS NULL;

-- 4
SELECT CODIGO, NOMBRE
FROM salas
WHERE PELICULA IS NULL;

-- 5
SELECT s.CODIGO, s.NOMBRE, p.NOMBRE AS PELICULA, p.CALIFICACIONEDAD
FROM salas s
LEFT JOIN peliculas p ON s.PELICULA = p.CODIGO;

-- 6
SELECT p.CODIGO AS CODIGO_PELICULA, p.NOMBRE AS NOMBRE_PELICULA, p.CALIFICACIONEDAD, s.CODIGO AS CODIGO_SALA, s.NOMBRE AS NOMBRE_SALA
FROM peliculas p
LEFT JOIN salas s ON p.CODIGO = s.PELICULA;

-- 7
SELECT p.NOMBRE AS NOMBRE_PELICULA
FROM peliculas p
LEFT JOIN salas s ON p.CODIGO = s.PELICULA
WHERE s.CODIGO IS NULL;

-- 8
INSERT INTO peliculas (NOMBRE, CALIFICACIONEDAD)
VALUES ('Uno, Dos, Tres', 'PG-7');

-- 9
UPDATE peliculas
SET CALIFICACIONEDAD = 'PG-13'
WHERE CALIFICACIONEDAD IS NULL;

-- 10
DELETE FROM salas
WHERE PELICULA IN (
    SELECT CODIGO FROM peliculas WHERE CALIFICACIONEDAD = 'G'
);